import{a as q,S as v,i as n}from"./assets/vendor-Db2TdIkw.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const P="https://pixabay.com/api/",B="49650006-f0ae027caead239649e4c06a7";async function u(r,t=1){const s={key:B,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await q.get(P,{params:s})).data}const m=document.querySelector(".gallery"),g=document.querySelector(".loader"),R=new v(".gallery a",{captionsData:"alt",captionDelay:250});function f(r){const t=r.map(({webformatURL:s,largeImageURL:a,tags:e,likes:o,views:i,comments:w,downloads:S})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${a}">
          <img class="gallery-image" src="${s}" alt="${e}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${o}</p>
          <p><b>Views:</b> ${i}</p>
          <p><b>Comments:</b> ${w}</p>
          <p><b>Downloads:</b> ${S}</p>
        </div>
      </li>
    `).join("");m.insertAdjacentHTML("beforeend",t),R.refresh()}function $(){m.innerHTML=""}function p(){g.classList.remove("is-hidden")}function h(){g.classList.add("is-hidden")}function y(){document.querySelector(".load-more").classList.remove("is-hidden")}function L(){document.querySelector(".load-more").classList.add("is-hidden")}const d=document.querySelector(".form");let l="",c=1,b=0;d.addEventListener("submit",async r=>{if(r.preventDefault(),l=d.elements["search-text"].value.trim(),c=1,$(),L(),l===""){n.warning({message:"Please enter a search term!",position:"topRight"});return}p();try{const t=await u(l,c);if(b=t.totalHits,t.hits.length===0){n.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}f(t.hits),t.totalHits>15&&y()}catch{n.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{h(),d.reset()}});const E=document.querySelector(".load-more");E.addEventListener("click",async()=>{c+=1,p(),L();try{const r=await u(l,c);f(r.hits);const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),document.querySelectorAll(".gallery-item").length>=b?n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):y()}catch{n.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{h()}});
//# sourceMappingURL=index.js.map
